version: '3'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  # MongoDB database
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"

  # Node.js application
  app:
    image: duplo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_HOST: postgres
      PG_PORT: ${PG_PORT}
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DBNAME: ${MONGO_DBNAME}
      ENV_PROFILE: ${ENV_PROFILE}
      WAIT_HOSTS: postgres:5432, mongo:27017
      WAIT_TIMEOUT: 300
    depends_on:
      - postgres
      - mongodb