version: '3'

services:
  node-app:
    image: your-node-app-image:latest
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
      - mongodb

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your-postgres-database
      POSTGRES_USER: your-postgres-username
      POSTGRES_PASSWORD: your-postgres-password

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-mongodb-username
      MONGO_INITDB_ROOT_PASSWORD: your-mongodb-password
